### ISSUE TITLE
Hide reducibility parameters?

### ISSUE THREAD

**Issue by nad** [graded-type-theory/graded-type-theory#7]
Some definitions are parametrised by reducibility arguments, and quite a bit of code has been written to ensure that these parameters are correct. It might make sense to add alternative definitions without such parameters, similarly to the code in `Graded.Erasure.LogicalRelation.Hidden`.

**Comment by nad** [comment]
I have added such alternative definitions, and converted those parts of the proofs of the fundamental lemmas that relate to variables, U, Unit, Id and ℕ. However, those parts of the proofs that relate to Empty, Π and Σ have not yet been converted.

**Comment by oskeri** [comment]
I have converted the parts that relate to Empty

**Comment by nad** [comment]
The parts that relate to Π and Σ have also been converted. I think it might make sense to also remove `_⊩ᵛ⟨_⟩_/_` in favour of (a new definition of) `_⊩ᵛ⟨_⟩_`, and similarly for `_⊩ˢ_∷_/_/_`, `_⊩ˢ_≡_∷_/_/_/_`, `_⊩ᵛ⟨_⟩_∷_/_/_`, `_⊩ᵛ⟨_⟩_≡_/_/_` and `_⊩ᵛ⟨_⟩_≡_∷_/_/_`.
